### ISSUE TITLE
Use English as convention in your code base

### ISSUE THREAD

**Issue by Chemaclass** [CosmeValera/LeagueOfPokemon#5]
Currently, you're mixing Spanish and English for your variables and function names. I strongly suggest standardized this to one language; either Spanish OR English, but not both.

On this matter, and due to the reality, I would suggest using English by default, because it's the standard language in this industry, so it will help you to get easier into the flow of what's coming ;)

PS: Also, you will get used to it easy peasy.

**Comment by CosmeValera** [comment]
I released version 0.2.0 and now everything is translated to English
